-- within this file will be SQL code specifically designed to cater the creation of tables needed for this project within ORACLE --
-- H1: weather vs severity

-- code below is for creating the dimension tables --

-- Drop DIMENSION tables --
DROP TABLE DIM_DATE CASCADE CONSTRAINTS;
DROP TABLE DIM_WEATHER CASCADE CONSTRAINTS;
DROP TABLE DIM_LIGHTING CASCADE CONSTRAINTS;
DROP TABLE DIM_ROAD CASCADE CONSTRAINTS;
DROP TABLE DIM_VEHICLE CASCADE CONSTRAINTS;
DROP TABLE DIM_CASUALTY CASCADE CONSTRAINTS;





CREATE TABLE DIM_DATE (
    DATE_KEY            NUMBER PRIMARY KEY,
    FULL_DATE           DATE,
    DAY                 NUMBER,
    MONTH               VARCHAR2(20),
    QUARTER             NUMBER,
    YEAR                NUMBER,
    HOUR                NUMBER,
    TIME_PERIOD         VARCHAR2(20)
);

CREATE TABLE DIM_WEATHER (
    WEATHER_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WEATHER_CODE NUMBER,
    WEATHER_DESCRIPTION VARCHAR2(100)
);
-- weather table uses weather key which is automatically generated in incremental steps -- 
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (1, 'Fine without high winds');
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (2, 'Raining without high winds');
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (3, 'Snowing without high winds');
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (4, 'Fine with high winds');
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (5, 'Raining with high winds');
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (6, 'Snowing with high winds');
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (7, 'Fog or mist – if hazard');
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (8, 'Other');
INSERT INTO DIM_WEATHER (WEATHER_CODE, WEATHER_DESCRIPTION)
VALUES (9, 'Unknown');



CREATE TABLE DIM_LIGHTING (
    LIGHTING_KEY            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LIGHTING_CODE           NUMBER,
    LIGHTING_DESCRIPTION    VARCHAR2(100)
);
INSERT INTO DIM_LIGHTING (LIGHTING_CODE, LIGHTING_DESCRIPTION)
VALUES (1, 'Daylight: street lights present');
INSERT INTO DIM_LIGHTING (LIGHTING_CODE, LIGHTING_DESCRIPTION)
VALUES (2, 'Daylight: no street lighting');
INSERT INTO DIM_LIGHTING (LIGHTING_CODE, LIGHTING_DESCRIPTION)
VALUES (3, 'Daylight: street lighting unknown');
INSERT INTO DIM_LIGHTING (LIGHTING_CODE, LIGHTING_DESCRIPTION)
VALUES (4, 'Darkness: street lights present and lit');
INSERT INTO DIM_LIGHTING (LIGHTING_CODE, LIGHTING_DESCRIPTION)
VALUES (5, 'Darkness: street lights present but unlit');
INSERT INTO DIM_LIGHTING (LIGHTING_CODE, LIGHTING_DESCRIPTION)
VALUES (6, 'Darkness: no street lighting');
INSERT INTO DIM_LIGHTING (LIGHTING_CODE, LIGHTING_DESCRIPTION)
VALUES (7, 'Darkness: street lighting unknown');


CREATE TABLE DIM_ROAD (
    ROAD_KEY                    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROAD_SURFACE_CODE           NUMBER,
    ROAD_SURFACE_DESCRIPTION    VARCHAR2(100)
);



INSERT INTO DIM_ROAD (ROAD_SURFACE_CODE, ROAD_SURFACE_DESCRIPTION)
VALUES (1, 'Dry');
INSERT INTO DIM_ROAD (ROAD_SURFACE_CODE, ROAD_SURFACE_DESCRIPTION)
VALUES (2, 'Wet / Damp');
INSERT INTO DIM_ROAD (ROAD_SURFACE_CODE, ROAD_SURFACE_DESCRIPTION)
VALUES (3, 'Snow');
INSERT INTO DIM_ROAD (ROAD_SURFACE_CODE, ROAD_SURFACE_DESCRIPTION)
VALUES (4, 'Frost / Ice');
INSERT INTO DIM_ROAD (ROAD_SURFACE_CODE, ROAD_SURFACE_DESCRIPTION)
VALUES (5, 'Flood (surface water over 3cm deep)');
INSERT INTO DIM_ROAD (ROAD_SURFACE_CODE, ROAD_SURFACE_DESCRIPTION)
VALUES (9, 'Unknown');



CREATE TABLE DIM_VEHICLE (
    VEHICLE_KEY             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VEHICLE_TYPE_CODE       NUMBER,
    VEHICLE_DESCRIPTION     VARCHAR2(100)
);

INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (1, 'Pedal cycle');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (2, 'M/cycle 50cc and under');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (3, 'Motorcycle over 50cc and up to 125cc');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (4, 'Motorcycle over 125cc and up to 500cc');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (5, 'Motorcycle over 500cc');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (6, '[Not used]');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (7, '[Not used]');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (8, 'Taxi/Private hire car');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (9, 'Car');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (10, 'Minibus (8–16 passenger seats)');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (11, 'Bus or coach (17 or more passenger seats)');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (12, '[Not used]');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (13, '[Not used]');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (14, 'Other motor vehicle');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (15, 'Other non-motor vehicle');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (16, 'Ridden horse');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (17, 'Agricultural vehicle (includes diggers etc.)');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (18, 'Tram / Light rail');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (19, 'Goods vehicle 3.5 tonnes mgw and under');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (20, 'Goods vehicle over 3.5 tonnes and under 7.5 tonnes mgw');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (21, 'Goods vehicle 7.5 tonnes mgw and over');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (22, 'Mobility Scooter');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (23, 'Electric motorcycle');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (90, 'Other Vehicle');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (97, 'Motorcycle - Unknown CC');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (98, 'Goods vehicle - unknown weight');
INSERT INTO DIM_VEHICLE (VEHICLE_TYPE_CODE, VEHICLE_DESCRIPTION)
VALUES (99, 'Unknown vehicle type');

CREATE TABLE DIM_CASUALTY (
    CASUALTY_KEY            NUMBER PRIMARY KEY,
    CASUALTY_CLASS          VARCHAR2(50),
    SEX_OF_CASUALTY         VARCHAR2(20),
    AGE_OF_CASUALTY         NUMBER,
    AGE_BAND                NUMBER,
    CASUALTY_SEVERITY       VARCHAR2(50)
);

-- CASUALTY CLASS
INSERT INTO DIM_CASUALTY (CASUALTY_KEY, CASUALTY_CLASS)
VALUES (1, 'Driver or rider');
INSERT INTO DIM_CASUALTY (CASUALTY_KEY, CASUALTY_CLASS)
VALUES (2, 'Vehicle or pillion passenger');  
INSERT INTO DIM_CASUALTY (CASUALTY_KEY, CASUALTY_CLASS)  
VALUES (3, 'Pedestrian');

-- CASUALTY SEVERITY
INSERT INTO DIM_CASUALTY (CASUALTY_KEY, CASUALTY_SEVERITY)
VALUES (42, 'Fatal');
INSERT INTO DIM_CASUALTY (CASUALTY_KEY, CASUALTY_SEVERITY)
VALUES (43, 'Serious');
INSERT INTO DIM_CASUALTY (CASUALTY_KEY, CASUALTY_SEVERITY)
VALUES (44, 'Slight');

-- SEX OF CASUALTY
INSERT INTO DIM_CASUALTY (CASUALTY_KEY, SEX_OF_CASUALTY)
VALUES (47, 'Male');
INSERT INTO DIM_CASUALTY (CASUALTY_KEY, SEX_OF_CASUALTY)
VALUES (48, 'Female');

CREATE TABLE FACT_INCIDENT (
    INCIDENT_KEY                NUMBER PRIMARY KEY,
    REFERENCE_NUMBER            NUMBER,

    DATE_KEY                    NUMBER,
    WEATHER_KEY                 NUMBER,
    LIGHTING_KEY                NUMBER,
    ROAD_KEY                    NUMBER,
    CASUALTY_KEY                NUMBER,
    VEHICLE_KEY                 NUMBER,

    NUMBER_OF_VEHICLES          NUMBER,
    CASUALTY_NUMBER             NUMBER,
    CASUALTY_SEVERITY_CODE      NUMBER,
    INCIDENT_COUNT              NUMBER,

    CONSTRAINT FK_FACT_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY),

    CONSTRAINT FK_FACT_WEATHER
        FOREIGN KEY (WEATHER_KEY)
        REFERENCES DIM_WEATHER(WEATHER_KEY),

    CONSTRAINT FK_FACT_LIGHTING
        FOREIGN KEY (LIGHTING_KEY)
        REFERENCES DIM_LIGHTING(LIGHTING_KEY),

    CONSTRAINT FK_FACT_ROAD
        FOREIGN KEY (ROAD_KEY)
        REFERENCES DIM_ROAD(ROAD_KEY),

    CONSTRAINT FK_FACT_CASUALTY
        FOREIGN KEY (CASUALTY_KEY)
        REFERENCES DIM_CASUALTY(CASUALTY_KEY),

    CONSTRAINT FK_FACT_VEHICLE
        FOREIGN KEY (VEHICLE_KEY)
        REFERENCES DIM_VEHICLE(VEHICLE_KEY)
);
DROP TABLE STAGING_INCIDENT CASCADE CONSTRAINTS;
CREATE TABLE STAGING_INCIDENT (
    REFERENCE_NUMBER varchar2(20),
    NUMBER_OF_VEHICLES NUMBER,
    FULL_DATE VARCHAR2(10),
    FULL_TIME VARCHAR2(4),
    ROAD_CLASS NUMBER,
    ROAD_SURFACE_CODE NUMBER,
    LIGHTING_CODE NUMBER,
    WEATHER_CODE NUMBER,
    CASUALTY_NUMBER NUMBER,
    CASUALTY_CLASS NUMBER,
    SEX_OF_CASUALTY NUMBER,
    AGE_OF_CASUALTY NUMBER,
    CASUALTY_SEVERITY NUMBER,
    VEHICLE_1 NUMBER,
    VEHICLE_2 NUMBER,
    VEHICLE_3 NUMBER,
    VEHICLE_4 NUMBER,
    VEHICLE_5 NUMBER,
    VEHICLE_6 NUMBER,
    VEHICLE_7 NUMBER,
    VEHICLE_8 NUMBER,
    VEHICLE_9 NUMBER,
    VEHICLE_10 NUMBER
);
DROP SEQUENCE FACT_INCIDENT_SEQ;

CREATE SEQUENCE FACT_INCIDENT_SEQ START WITH 1 INCREMENT BY 1;


INSERT INTO DIM_DATE (DATE_KEY, FULL_DATE, DAY, MONTH, QUARTER, YEAR, HOUR, TIME_PERIOD)
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(TO_DATE(FULL_DATE,'DD/MM/YYYY'),'YYYYMMDD')) AS DATE_KEY,
    TO_DATE(FULL_DATE,'DD/MM/YYYY'),
    TO_NUMBER(TO_CHAR(TO_DATE(FULL_DATE,'DD/MM/YYYY'),'DD')),
    TO_CHAR(TO_DATE(FULL_DATE,'DD/MM/YYYY'),'Month'),
    TO_NUMBER(TO_CHAR(TO_DATE(FULL_DATE,'DD/MM/YYYY'),'Q')),
    TO_NUMBER(TO_CHAR(TO_DATE(FULL_DATE,'DD/MM/YYYY'),'YYYY')),
    SUBSTR(FULL_TIME,1,2),
    CASE WHEN SUBSTR(FULL_TIME,1,2) BETWEEN '06' AND '11' THEN 'Morning'
         WHEN SUBSTR(FULL_TIME,1,2) BETWEEN '12' AND '17' THEN 'Afternoon'
         WHEN SUBSTR(FULL_TIME,1,2) BETWEEN '18' AND '23' THEN 'Evening'
         ELSE 'Night'
    END
FROM STAGING_INCIDENT;


drop table STAGING_LEEDS2016 cascade constraints;
CREATE TABLE STAGING_LEEDS2016 (
    REFERENCE_NUMBER VARCHAR2(20),
    EASTING NUMBER,
    NORTHING NUMBER,
    NUMBER_OF_VEHICLES NUMBER,
    ACCIDENT_DATE VARCHAR2(20),
    TIME_24HR VARCHAR2(10),
    ROAD_CLASS VARCHAR2(20),
    ROAD_SURFACE VARCHAR2(50),
    LIGHTING_CONDITIONS VARCHAR2(100),
    WEATHER_CONDITIONS VARCHAR2(100),
    CASUALTY_CLASS VARCHAR2(50),
    CASUALTY_SEVERITY VARCHAR2(50),
    SEX_OF_CASUALTY VARCHAR2(10),
    AGE_OF_CASUALTY NUMBER,
    VEHICLE_TYPE VARCHAR2(100)
);
drop table Staging_weather cascade constraints;
CREATE TABLE STAGING_WEATHER (
    RECORD_DATETIME      TIMESTAMP,     
    WIND_DIRECTION       NUMBER(5,2),   
    WIND_SPEED           NUMBER(5,2),   
    WIND_STD             NUMBER(5,2),   
    TEMP_8M              NUMBER(5,2),  
    TEMP_DIFF            NUMBER(5,2),   
    GLOBAL_RADIATION     NUMBER(10,2),  
    REL_HUMIDITY         NUMBER(5,2)    
);


-- these are views that are used to create graphs on the dashboard on an applocation within oracle Apex 
-- 1A raw contingency table (weather x severity) -- for chi-square export
-- / Interactive Report
CREATE OR REPLACE VIEW V_WEATHER_SEVERITY_RAW AS
SELECT
    d.YEAR,
    w.WEATHER_DESCRIPTION,
    sv.CASUALTY_SEVERITY_DESC,
    COUNT(*) AS incident_count
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_DATE     d  ON d.DATE_KEY    = f.DATE_KEY
JOIN DIM_WEATHER  w  ON w.WEATHER_KEY  = f.WEATHER_KEY
JOIN DIM_SEVERITY sv ON sv.SEVERITY_KEY = f.SEVERITY_KEY
GROUP BY d.YEAR, w.WEATHER_DESCRIPTION, sv.CASUALTY_SEVERITY_DESC;

-- 1B pivoted fatal/serious/slight counts by weather -- feeds the stacked bar
CREATE OR REPLACE VIEW V_WEATHER_SEVERITY AS
SELECT
    w.WEATHER_DESCRIPTION,
    SUM(CASE WHEN sv.CASUALTY_SEVERITY_DESC = 'Fatal'   THEN 1 ELSE 0 END) AS fatal,
    SUM(CASE WHEN sv.CASUALTY_SEVERITY_DESC = 'Serious' THEN 1 ELSE 0 END) AS serious,
    SUM(CASE WHEN sv.CASUALTY_SEVERITY_DESC = 'Slight'  THEN 1 ELSE 0 END) AS slight,
    COUNT(*) AS total
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_WEATHER  w  ON w.WEATHER_KEY  = f.WEATHER_KEY
JOIN DIM_SEVERITY sv ON sv.SEVERITY_KEY = f.SEVERITY_KEY
GROUP BY w.WEATHER_DESCRIPTION;

-- 1C Fine vs Adverse weather group, with average severity score -- 
CREATE OR REPLACE VIEW V_WEATHER_GROUP_SEVERITY AS
SELECT
    CASE WHEN w.WEATHER_DESCRIPTION LIKE 'Fine%' THEN 'Fine' ELSE 'Adverse' END AS weather_group,
    COUNT(*) AS incident_count,
    ROUND(AVG(4 - f.CASUALTY_SEVERITY_CODE), 2) AS avg_severity_score -- higher = more severe
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_WEATHER w ON w.WEATHER_KEY = f.WEATHER_KEY
WHERE f.CASUALTY_SEVERITY_CODE IS NOT NULL
GROUP BY CASE WHEN w.WEATHER_DESCRIPTION LIKE 'Fine%' THEN 'Fine' ELSE 'Adverse' END;



-- H2: visibility (lighting + fog) vs severity


-- 2a full lighting breakdown -- Interactive Report / detail drill-down
CREATE OR REPLACE VIEW V_LIGHTING_SEVERITY_RAW AS
SELECT
    d.YEAR,
    l.LIGHTING_DESCRIPTION,
    sv.CASUALTY_SEVERITY_DESC,
    COUNT(*) AS incident_count
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_DATE     d ON d.DATE_KEY     = f.DATE_KEY
JOIN DIM_LIGHTING l ON l.LIGHTING_KEY = f.LIGHTING_KEY
JOIN DIM_SEVERITY sv ON sv.SEVERITY_KEY = f.SEVERITY_KEY
GROUP BY d.YEAR, l.LIGHTING_DESCRIPTION, sv.CASUALTY_SEVERITY_DESC;

-- i sadly cant get these to work but in the future i will attempt to make these gauge charts
-- 2b Daylight vs Darkness, with % severe -- feeds the bar/gauge chart
-- 2c combined visibility hit: darkness OR fog/mist -- feeds a second bar/gauge chart




-- H3: rain vs incident frequency


-- 3a overall rain vs no-rain summary -- feeds a simple bar chart / KPI cards
CREATE OR REPLACE VIEW V_RAIN_OVERALL AS
SELECT
    CASE WHEN w.WEATHER_DESCRIPTION LIKE 'Raining%' THEN 'Rain' ELSE 'No rain' END AS rain_flag,
    COUNT(*) AS incident_count,
    COUNT(DISTINCT d.DATE_KEY) AS distinct_days_with_an_incident,
    ROUND(COUNT(*) / COUNT(DISTINCT d.DATE_KEY), 2) AS incidents_per_active_day
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_DATE    d ON d.DATE_KEY   = f.DATE_KEY
JOIN DIM_WEATHER w ON w.WEATHER_KEY = f.WEATHER_KEY
GROUP BY CASE WHEN w.WEATHER_DESCRIPTION LIKE 'Raining%' THEN 'Rain' ELSE 'No rain' END;

-- 3b monthly trend, rain vs no rain -- feeds the time-series line chart
CREATE OR REPLACE VIEW V_RAIN_TREND AS
SELECT
    d.YEAR,
    TO_CHAR(d.FULL_DATE, 'MM') AS month_num,
    CASE WHEN w.WEATHER_DESCRIPTION LIKE 'Raining%' THEN 'Rain' ELSE 'No rain' END AS rain_flag,
    COUNT(*) AS incident_count
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_DATE    d ON d.DATE_KEY   = f.DATE_KEY
JOIN DIM_WEATHER w ON w.WEATHER_KEY = f.WEATHER_KEY
GROUP BY d.YEAR, TO_CHAR(d.FULL_DATE, 'MM'),
         CASE WHEN w.WEATHER_DESCRIPTION LIKE 'Raining%' THEN 'Rain' ELSE 'No rain' END;




-- H4: seasonal variation vs severity


-- 4a severity distribution by season -- feeds the grouped/stacked bar chart
CREATE OR REPLACE VIEW V_SEASONAL_SEVERITY AS
SELECT
    CASE TO_CHAR(d.FULL_DATE, 'MM')
        WHEN '12' THEN 'Winter' WHEN '01' THEN 'Winter' WHEN '02' THEN 'Winter'
        WHEN '03' THEN 'Spring' WHEN '04' THEN 'Spring' WHEN '05' THEN 'Spring'
        WHEN '06' THEN 'Summer' WHEN '07' THEN 'Summer' WHEN '08' THEN 'Summer'
        WHEN '09' THEN 'Autumn' WHEN '10' THEN 'Autumn' WHEN '11' THEN 'Autumn'
    END AS season,
    sv.CASUALTY_SEVERITY_DESC,
    COUNT(*) AS incident_count
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_DATE     d  ON d.DATE_KEY   = f.DATE_KEY
JOIN DIM_SEVERITY sv ON sv.SEVERITY_KEY = f.SEVERITY_KEY
GROUP BY CASE TO_CHAR(d.FULL_DATE, 'MM')
        WHEN '12' THEN 'Winter' WHEN '01' THEN 'Winter' WHEN '02' THEN 'Winter'
        WHEN '03' THEN 'Spring' WHEN '04' THEN 'Spring' WHEN '05' THEN 'Spring'
        WHEN '06' THEN 'Summer' WHEN '07' THEN 'Summer' WHEN '08' THEN 'Summer'
        WHEN '09' THEN 'Autumn' WHEN '10' THEN 'Autumn' WHEN '11' THEN 'Autumn'
    END,
    sv.CASUALTY_SEVERITY_DESC;

-- 4b seasonal weather context (avg temp/wind/humidity) feeds KPI cards
-- or a small multi-series line chart alongside 4a
CREATE OR REPLACE VIEW V_SEASONAL_WEATHER AS
SELECT
    CASE TO_CHAR(d.FULL_DATE, 'MM')
        WHEN '12' THEN 'Winter' WHEN '01' THEN 'Winter' WHEN '02' THEN 'Winter'
        WHEN '03' THEN 'Spring' WHEN '04' THEN 'Spring' WHEN '05' THEN 'Spring'
        WHEN '06' THEN 'Summer' WHEN '07' THEN 'Summer' WHEN '08' THEN 'Summer'
        WHEN '09' THEN 'Autumn' WHEN '10' THEN 'Autumn' WHEN '11' THEN 'Autumn'
    END AS season,
    ROUND(AVG(f.WX_TEMP_8M_DEGC), 1)     AS avg_temp_c,
    ROUND(AVG(f.WX_WIND_SPD_12M_MS), 1)  AS avg_wind_speed_ms,
    ROUND(AVG(f.WX_REL_HUM_PCT), 1)      AS avg_humidity_pct,
    COUNT(*) AS incident_count
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
GROUP BY CASE TO_CHAR(d.FULL_DATE, 'MM')
        WHEN '12' THEN 'Winter' WHEN '01' THEN 'Winter' WHEN '02' THEN 'Winter'
        WHEN '03' THEN 'Spring' WHEN '04' THEN 'Spring' WHEN '05' THEN 'Spring'
        WHEN '06' THEN 'Summer' WHEN '07' THEN 'Summer' WHEN '08' THEN 'Summer'
        WHEN '09' THEN 'Autumn' WHEN '10' THEN 'Autumn' WHEN '11' THEN 'Autumn'
    END;



-- H5: flat extract for temporal-vs-weather model comparison

CREATE OR REPLACE VIEW V_H5_EXTRACT AS
SELECT
    f.INCIDENT_KEY,
    f.CASUALTY_SEVERITY_CODE,                         -- target: 1=Fatal, 2=Serious, 3=Slight
    4 - f.CASUALTY_SEVERITY_CODE          AS severity_score,  -- same target, higher = more severe

    
    d.YEAR,
    TO_CHAR(d.FULL_DATE, 'MM')            AS month_num,
    TO_CHAR(d.FULL_DATE, 'DY')            AS day_of_week,
    f.HOUR,
    f.TIME_PERIOD,
    CASE TO_CHAR(d.FULL_DATE, 'MM')
        WHEN '12' THEN 'Winter' WHEN '01' THEN 'Winter' WHEN '02' THEN 'Winter'
        WHEN '03' THEN 'Spring' WHEN '04' THEN 'Spring' WHEN '05' THEN 'Spring'
        WHEN '06' THEN 'Summer' WHEN '07' THEN 'Summer' WHEN '08' THEN 'Summer'
        WHEN '09' THEN 'Autumn' WHEN '10' THEN 'Autumn' WHEN '11' THEN 'Autumn'
    END AS season,

   
    w.WEATHER_DESCRIPTION,
    l.LIGHTING_DESCRIPTION,
    r.ROAD_SURFACE_DESCRIPTION,
    f.WX_WIND_DIR_12M,
    f.WX_WIND_SPD_12M_MS,
    f.WX_WIND_STD,
    f.WX_TEMP_8M_DEGC,
    f.WX_TEMP_DIFF_2M,
    f.WX_GLOB_RAD_WM2,
    f.WX_REL_HUM_PCT,
    f.WEATHER_TIME_GAP_MINUTES,          

    
    f.ROAD_CLASS,
    f.NUMBER_OF_VEHICLES,
    v.VEHICLE_DESCRIPTION
FROM FACT_INCIDENT_WEATHER f
JOIN DIM_DATE     d  ON d.DATE_KEY    = f.DATE_KEY
LEFT JOIN DIM_WEATHER  w ON w.WEATHER_KEY  = f.WEATHER_KEY
LEFT JOIN DIM_LIGHTING l ON l.LIGHTING_KEY = f.LIGHTING_KEY
LEFT JOIN DIM_ROAD     r ON r.ROAD_KEY     = f.ROAD_KEY
LEFT JOIN DIM_VEHICLE  v ON v.VEHICLE_KEY  = f.VEHICLE_KEY
WHERE f.CASUALTY_SEVERITY_CODE IS NOT NULL
  AND f.WEATHER_TIME_GAP_MINUTES IS NOT NULL
  AND f.WEATHER_TIME_GAP_MINUTES <= 1440
