-- file containing processes within an ETL stage that will clean the original loaded data to make it Uniform --

-- code for ETL stage on the staging area_Leeds2016 table -- 
SELECT * FROM STAGING_LEEDS2016;
ALTER TABLE STAGING_LEEDS2016 ADD (
    ROAD_CLASS_CODE NUMBER,
    ROAD_SURFACE_CODE NUMBER,
    LIGHTING_CODE NUMBER,
    WEATHER_CODE NUMBER
);
UPDATE STAGING_LEEDS2016
SET ROAD_CLASS_CODE = CASE
    WHEN ROAD_CLASS = 'Motorway' THEN 1
    WHEN ROAD_CLASS = 'A(M)' THEN 2
    WHEN ROAD_CLASS = 'A' THEN 3
    WHEN ROAD_CLASS = 'B' THEN 4
    WHEN ROAD_CLASS = 'C' THEN 5
    WHEN ROAD_CLASS = 'Unclassified' THEN 6
    ELSE NULL
END;
UPDATE STAGING_LEEDS2016
SET ROAD_SURFACE_CODE = CASE
    WHEN ROAD_SURFACE = 'Dry' THEN 1
    WHEN ROAD_SURFACE = 'Wet / Damp' THEN 2
    WHEN ROAD_SURFACE = 'Snow' THEN 3
    WHEN ROAD_SURFACE = 'Frost / Ice' THEN 4
    WHEN ROAD_SURFACE = 'Flood (surface water over 3cm deep)' THEN 5
    WHEN ROAD_SURFACE = 'Unknown' THEN 9
    ELSE NULL
END;
UPDATE STAGING_LEEDS2016
SET LIGHTING_CODE = CASE
    WHEN LIGHTING_CONDITIONS = 'Daylight: street lights present' THEN 1
    WHEN LIGHTING_CONDITIONS = 'Daylight: no street lighting' THEN 2
    WHEN LIGHTING_CONDITIONS = 'Daylight: street lighting unknown' THEN 3
    WHEN LIGHTING_CONDITIONS = 'Darkness: street lights present and lit' THEN 4
    WHEN LIGHTING_CONDITIONS = 'Darkness: street lights present but unlit' THEN 5
    WHEN LIGHTING_CONDITIONS = 'Darkness: no street lighting' THEN 6
    WHEN LIGHTING_CONDITIONS = 'Darkness: street lighting unknown' THEN 7
    ELSE NULL
END;
UPDATE STAGING_LEEDS2016
SET WEATHER_CODE = CASE
    WHEN WEATHER_CONDITIONS = 'Fine without high winds' THEN 1
    WHEN WEATHER_CONDITIONS = 'Raining without high winds' THEN 2
    WHEN WEATHER_CONDITIONS = 'Snowing without high winds' THEN 3
    WHEN WEATHER_CONDITIONS = 'Fine with high winds' THEN 4
    WHEN WEATHER_CONDITIONS = 'Raining with high winds' THEN 5
    WHEN WEATHER_CONDITIONS = 'Snowing with high winds' THEN 6
    WHEN WEATHER_CONDITIONS = 'Fog or mist – if hazard' THEN 7
    WHEN WEATHER_CONDITIONS = 'Other' THEN 8
    WHEN WEATHER_CONDITIONS = 'Unknown' THEN 9
    ELSE NULL
END;

SELECT ROAD_CLASS, ROAD_CLASS_CODE,
       ROAD_SURFACE, ROAD_SURFACE_CODE,
       LIGHTING_CONDITIONS, LIGHTING_CODE,
       WEATHER_CONDITIONS, WEATHER_CODE
FROM STAGING_LEEDS2016
FETCH FIRST 50 ROWS ONLY;

ALTER TABLE STAGING_LEEDS2016 ADD (
    CASUALTY_CLASS_CODE NUMBER,
    CASUALTY_SEVERITY_CODE NUMBER,
    SEX_OF_CASUALTY_CODE NUMBER,
    AGE_OF_CASUALTY_CODE NUMBER,
    VEHICLE_TYPE_CODE NUMBER
);

UPDATE STAGING_LEEDS2016
SET CASUALTY_CLASS_CODE = CASE
    WHEN CASUALTY_CLASS = 'Driver or rider' THEN 1
    WHEN CASUALTY_CLASS = 'Vehicle or pillion passenger' THEN 2
    WHEN CASUALTY_CLASS = 'Pedestrian' THEN 3
    ELSE NULL
END;
UPDATE STAGING_LEEDS2016
SET CASUALTY_SEVERITY_CODE = CASE
    WHEN CASUALTY_SEVERITY = 'Fatal' THEN 1
    WHEN CASUALTY_SEVERITY = 'Serious' THEN 2
    WHEN CASUALTY_SEVERITY = 'Slight' THEN 3
    ELSE NULL
END;
UPDATE STAGING_LEEDS2016
SET SEX_OF_CASUALTY_CODE = CASE
    WHEN SEX_OF_CASUALTY = 'Male' THEN 1
    WHEN SEX_OF_CASUALTY = 'Female' THEN 2
    ELSE NULL
END;
UPDATE STAGING_LEEDS2016
SET AGE_OF_CASUALTY_CODE = AGE_OF_CASUALTY;
UPDATE STAGING_LEEDS2016
SET VEHICLE_TYPE_CODE = CASE
    WHEN VEHICLE_TYPE = 'Pedal cycle' THEN 1
    WHEN VEHICLE_TYPE = 'M/cycle 50cc and under' THEN 2
    WHEN VEHICLE_TYPE = 'Motorcycle over 50cc and up to 125cc' THEN 3
    WHEN VEHICLE_TYPE = 'Motorcycle over 125cc and up to 500cc' THEN 4
    WHEN VEHICLE_TYPE = 'Motorcycle over 500cc' THEN 5
    WHEN VEHICLE_TYPE = 'Taxi/Private hire car' THEN 8
    WHEN VEHICLE_TYPE = 'Car' THEN 9
    WHEN VEHICLE_TYPE = 'Minibus (8–16 passenger seats)' THEN 10
    WHEN VEHICLE_TYPE = 'Bus or coach (17 or more passenger seats)' THEN 11
    WHEN VEHICLE_TYPE = 'Other motor vehicle' THEN 14
    WHEN VEHICLE_TYPE = 'Other non-motor vehicle' THEN 15
    WHEN VEHICLE_TYPE = 'Ridden horse' THEN 16
    WHEN VEHICLE_TYPE = 'Agricultural vehicle (includes diggers etc.)' THEN 17
    WHEN VEHICLE_TYPE = 'Tram / Light rail' THEN 18
    WHEN VEHICLE_TYPE = 'Goods vehicle 3.5 tonnes mgw and under' THEN 19
    WHEN VEHICLE_TYPE = 'Goods vehicle over 3.5 tonnes and under 7.5 tonnes mgw' THEN 20
    WHEN VEHICLE_TYPE = 'Goods vehicle 7.5 tonnes mgw and over' THEN 21
    WHEN VEHICLE_TYPE = 'Mobility Scooter' THEN 22
    WHEN VEHICLE_TYPE = 'Electric motorcycle' THEN 23
    WHEN VEHICLE_TYPE = 'Other Vehicle' THEN 90
    WHEN VEHICLE_TYPE = 'Motorcycle - Unknown CC' THEN 97
    WHEN VEHICLE_TYPE = 'Goods vehicle - unknown weight' THEN 98
    WHEN VEHICLE_TYPE = 'Unknown vehicle type' THEN 99
    ELSE NULL
    END;
    SELECT CASUALTY_CLASS, CASUALTY_CLASS_CODE,
       CASUALTY_SEVERITY, CASUALTY_SEVERITY_CODE,
       SEX_OF_CASUALTY, SEX_OF_CASUALTY_CODE,
       AGE_OF_CASUALTY, AGE_OF_CASUALTY_CODE,
       VEHICLE_TYPE, VEHICLE_TYPE_CODE
FROM STAGING_LEEDS2016
FETCH FIRST 50 ROWS ONLY;

UPDATE STAGING_LEEDS2016
SET TIME_24HR =
    SUBSTR(LPAD(TIME_24HR, 4, '0'), 1, 2) || ':' ||
    SUBSTR(LPAD(TIME_24HR, 4, '0'), 3, 2);


ALTER TABLE STAGING_INCIDENT
MODIFY FULL_TIME VARCHAR2(5);

UPDATE STAGING_incident
SET FULL_TIME =
    SUBSTR(LPAD(FULL_TIME, 4, '0'), 1, 2) || ':' ||
    SUBSTR(LPAD(FULL_TIME, 4, '0'), 3, 2);


ALTER TABLE STAGING_WEATHER ADD (
    DATE_ONLY VARCHAR2(10),
    TIME_ONLY VARCHAR2(5)
);
UPDATE STAGING_WEATHER
SET DATE_ONLY = TO_CHAR(RECORD_DATETIME, 'DD_MM_YYYY'),
    TIME_ONLY = TO_CHAR(RECORD_DATETIME, 'HH24:MI');
ALTER TABLE STAGING_INCIDENT_JOINED
MODIFY FULL_TIME VARCHAR2(8);
UPDATE STAGING_LEEDS2016
SET ACCIDENT_DATE = TO_DATE(ACCIDENT_DATE, 'DD/MM/RR');

-- this code changes incidents joined table to make it uniform for the weather data to join --
ALTER TABLE STAGING_INCIDENT_JOINED
MODIFY FULL_TIME VARCHAR2(8);

UPDATE STAGING_INCIDENT_JOINED
SET FULL_TIME =
    LPAD(
        SUBSTR(
            LPAD(REPLACE(FULL_TIME, ':', ''), 4, '0'),
            1, 2
        ), 2, '0'
    )
    || ':' ||
    LPAD(
        SUBSTR(
            LPAD(REPLACE(FULL_TIME, ':', ''), 4, '0'),
            3, 2
        ), 2, '0'
    );
select * from STAGING_INCIDENT_JOINED
ALTER TABLE STAGING_INCIDENT_JOINED
MODIFY FULL_DATE DATE;
UPDATE STAGING_INCIDENT_JOINED
SET FULL_DATE = TO_DATE(FULL_DATE, 'DD/MM/YYYY');
SELECT
    TO_CHAR(FULL_DATE, 'DD/MM/YYYY') AS FULL_DATE
FROM STAGING_INCIDENT_JOINED;
UPDATE STAGING_INCIDENT_JOINED
SET FULL_DATE = TO_DATE(FULL_DATE, 'DD/MM/RR');
